version: '3.8'

services:
  api-gateway:
    build: 
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    environment:
      - NODE_ENV=development
      - PORT=3100
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - MONGO_URI=${MONGO_URI}
      - RATE_LIMIT_WINDOW_MS=60000
      - RATE_LIMIT_MAX=100
    volumes:
      - ./services/api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - status-service

  status-service:
    build:
      context: ./services/status-service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=3101
      - MONGO_URI=${MONGO_URI}
      - STATUS_CHECK_INTERVAL=30000
    volumes:
      - ./services/status-service:/usr/src/app
      - /usr/src/app/node_modules