version: '3.8'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-example}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:-mwap_db}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  api-gateway:
    build: 
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    environment:
      - NODE_ENV=development
      - HEROKU_APP_NAME=mwap-local
      - PORT=3100
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - MONGO_URI=${MONGO_URI}
      - RATE_LIMIT_WINDOW_MS=60000
      - RATE_LIMIT_MAX=100
    volumes:
      - ./services/api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
      - status-service

  status-service:
    build:
      context: ./services/status-service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - HEROKU_APP_NAME=mwap-local
      - PORT=3101
      - MONGO_URI=${MONGO_URI}
      - STATUS_CHECK_INTERVAL=30000
    volumes:
      - ./services/status-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb

volumes:
  mongodb_data: